#Four Filled Squares
import turtle
turtle.setup(800,500)
turtle.pencolor("blue")
turtle.pensize(5)
turtle.speed(5)
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.left(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(180)
turtle.forward(200)
turtle.end_fill()
turtle.hideturtle()
turtle.done()