import turtle
turtle.setup(800,600)
turtle.shape("turtle")
turtle.showturtle()
turtle.pensize(2)
turtle.color("red")
turtle.speed(2)
turtle.goto(0,0)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
# turtle.hideturtle()
turtle.done()