# Olympics
import turtle
turtle.setup(800,500)
turtle.pensize(12)
turtle.speed(10)
turtle.pencolor("black")
turtle.circle(80)
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(80)
turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(80)
turtle.penup()
turtle.goto(-100,-100)
turtle.pendown()
turtle.pencolor("yellow")
turtle.circle(80)
turtle.penup()
turtle.goto(100,-100)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(80)
turtle.done()
