#Two Connected Shapes
import turtle
turtle.setup(800,500)
turtle.pensize(2)
turtle.speed(2)
turtle.pencolor("black")
turtle.fillcolor("orange")
turtle.begin_fill()
turtle.left(45)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
turtle.hideturtle()
turtle.done()
